module.exports = {
  docsSidebar: [
    "index",
    {
      type: "category",
      label: "Getting Started",
      items: [{ type: "autogenerated", dirName: "getting-started" }]
    },
    {
      type: "category",
      label: "Concepts",
      items: [{ type: "autogenerated", dirName: "concepts" }]
    },
    {
      type: "category",
      label: "Architecture",
      items: [{ type: "autogenerated", dirName: "architecture" }]
    },
    {
      type: "category",
      label: "Security",
      items: [{ type: "autogenerated", dirName: "security" }]
    },
    {
      type: "category",
      label: "Governance",
      items: [{ type: "autogenerated", dirName: "governance" }]
    },
    {
      type: "category",
      label: "Policies",
      items: [{ type: "autogenerated", dirName: "policies" }]
    },
    {
      type: "category",
      label: "Integrations",
      items: [{ type: "autogenerated", dirName: "integrations" }]
    },
    {
      type: "category",
      label: "SDK",
      items: [{ type: "autogenerated", dirName: "sdk" }]
    },
    {
      type: "category",
      label: "API Reference",
      items: [{ type: "autogenerated", dirName: "api" }]
    },
    {
      type: "category",
      label: "Examples",
      items: [{ type: "autogenerated", dirName: "examples" }]
    },
    {
      type: "category",
      label: "Reference",
      items: [{ type: "autogenerated", dirName: "reference" }]
    },
    {
      type: "category",
      label: "Releases",
      items: [{ type: "autogenerated", dirName: "releases" }]
    }
  ]
};